### PR TITLE
Treat <1 thread pools as 1

### PR DESCRIPTION
**Pull request by mitchellwrosen**
This patch removes a call to `error` by treating thread pools of size < 1 thread as size 1.

### CODE REVIEW

**Comment by mitchellwrosen** [comment]
Tests are failing - let me know if you want this change and I'll fix them :)

**Comment by snoyberg** [comment]
I'm pretty ambivalent about this change. @nh2 do you have any thoughts?

**Comment by nh2** [comment]
Is there any benefit to doing this?

I had considered this originally, but arrived at the conculusion that accepting nonsensical values without throwing hides more issues than it helps with.

**Comment by mitchellwrosen** [comment]
@nh2 Sounds like we just have the opposite opinion on this one, so feel free to close.

**Comment by nh2** [comment]
@mitchellwrosen I'm interested in hearing your opinion though. Usually people asking for changes have some kind of use case from which the opinion originates.

If somebody passes in `0` or `-1` or `-4234`, would that not indicate a severe bug in the calling code, likely due to an incorrect computation or memory corruption?

In what kind of situation would it it be tenable to continue, given that the passed-in IO computation might also suffer from this wrong computation or corruption, thus potentially doing something bad in IO (like shooting the rockets, in pooled parallel fashion)?

**Comment by mitchellwrosen** [comment]
Sure - I don't have a strong opinion one way or the other, I would simply prefer functions with _some_ sensible behavior to be total. In this particular case, running a "parallel" map on one thread seems likely to go wrong in a way that's acceptable to the application, or at least, not likely to cause a externally visible "bug" to the software user.

However, a negative input would likely indicate a logic in the program, and silently hiding a logic bug in a way that's difficult to notice (again, for this particular example, you might need some undesirably sophisticated monitoring to even notice that you're not hitting the expected performance) is arguably much worse.

Note that there is some precedent in base - list functions like `replicate` and `take` return the empty list on negative inputs, not `undefined`. But again, I see good arguments on both sides so I defer to your judgement here.

**Comment by nh2** [comment]
Thanks for the explanation! :+1: 

Your point about incorrect inputs being difficult to observe (needing performance analysis to spot missing parallelism in production) is also a good one.

I think in summary I remain in favour of the `error`ing function.

**Pull request closed without merging**
