### PR TITLE
Allow base-4.18

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Review by snoyberg — APPROVED** [review]

**Comment by mpilgrem** [comment]
@snoyberg, would it be possible to revise the package description on Hackage to also allow `base-4.18.0.0`?

**Comment by snoyberg** [comment]
I see `base < 5` for the latest release. What version (and revision) are you using?

**Comment by mpilgrem** [comment]
@snoyberg, I think you are looking at `unliftio-0.2.24.0` - this pull request relates to package `unliftio-core`, where version 0.2.1.0 still has `base >=4.9 && <4.18`.

**Comment by snoyberg** [comment]
Sorry about that, my mistake. Revision applied.

**Pull request merged**
